### PR TITLE
Scrap none values in multiselects

### PR DESCRIPTION
**Pull request by andylolz**
I don’t _think_ these are useful, and they don’t play nicely with chosen.

### CODE REVIEW

**Comment by hayfield** [comment]
Without chosen they're kinda useful in that it provides an obvious way to reset the selection (without wiping the whole page). With chosen, yeah, probably not needed!

**Comment by andylolz** [comment]
> Without chosen they're kinda useful in that it provides an obvious way to reset the selection (without wiping the whole page). With chosen, yeah, probably not needed!

Aha – so remove with javascript?

**Comment by hayfield** [comment]
> Aha – so remove with javascript?

That sounds like a good approach that works each with and without JS.

**Comment by andylolz** [comment]
Kk, sorted I think!

**Comment by allthatilk** [comment]
I might have gotten the wrong end of the stick here but I think the None values are inserted in the templates and can easy be removed without consequence so why don't we just do that?

**Comment by andylolz** [comment]
@allthatilk: yeah, they can be easily removed (that’s what I did originally in b49c32e8) but @hayfield makes the following point:

> Without chosen they're kinda useful in that it provides an obvious way to reset the selection (without wiping the whole page).

That seems reasonable to me, so I’ve reinstated them in the templates and instead remove them in javascript (in e666e40d).

**Comment by andylolz** [comment]
> Hmmm... There's some internal communication missing here as I'm still using chosen on my branch and it's still being used on `dev` too so I'm not sure what's been decided.

Not sure I follow. This PR doesn’t remove chosen. The diff looks slightly weird, but the line initialising chosen is just moved rather than removed:
https://github.com/IATI/IATI-Query-Builder/pull/67/files

**Comment by dalepotter** [comment]
This one looks good to me, if merge conflicts can be resolved I'll approve and merge into `dev`.

**Comment by hayfield** [comment]
This change is included in #76

**Comment by andylolz** [comment]
> This change is included in #76

It is indeed! Closing this one, then.

**Pull request closed without merging**
