### PR TITLE
Revert "Fix ugly ids"

### PR DESCRIPTION
**Pull request by hayfield**
Reverts IATI/IATI-Query-Builder#64

The change breaks many things

### CODE REVIEW

**Comment by andylolz** [comment]
> The change breaks many things

Can you be more specific? What does it break?

**Comment by hayfield** [comment]
all the JS

**Comment by andylolz** [comment]
> all the JS

Can you be even more specific? Here is the demo:
https://andylolz.github.io/IATI-Query-Builder/

Please tell me what is wrong and I will fix it. Given the number of times I have fixed merge conflicts on this branch, I feel invested in getting it merged now.

**Comment by allthatilk** [comment]
Merge conflict went wrong, don't worry, this will get merged. Working on it now.

**Pull request merged**
