### PR TITLE
Replace “generate link to CSV” button with “download CSV” button

### PR DESCRIPTION
**Pull request by andylolz**
download gif

I suspect that most users don’t care about the generated link – I think it’s just an extra interim step to getting the CSV. This PR cuts out that step, and turns the “submit the form” + “here’s your link” steps into a single “download the CSV” step.

### CODE REVIEW

**Comment by JamesCoe** [comment]
Fully behind this idea. When showing people the querybuilder i've found that people get confused why there is a link. A simple download button will make the UI much easier and require less / no explanation.

**Comment by hayfield** [comment]
> I suspect that most users don’t care about the generated link

As part of our user research, we have found that a number of users require the ability to share a link with others. As such, there is definitely demand for this.

**Comment by JamesCoe** [comment]
@hayfield -- any chance you can share a link/send over a write up of the user research? Genuinely interested.

**Comment by dalepotter** [comment]
@JamesCoe publicly we only have this written up at them moment: https://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733/5 <- but it does cover the query builder and datastore in some detail.

**Comment by andylolz** [comment]
From [that post](https://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733/5):

> Add ability to save queries for reuse

Ooh – I like that idea!

[Here’s a thing I made ages ago](http://scratchblocks.codeclub.org.uk/translator/#script=when%20green%20flag%20clicked%0Aforever%0A%20%20move%20%5B10%5D%20steps%0A%20%20turn%20right%20(15)%20degrees&from=en&to=fr) that does that by updating the URL hash onchange.

Doing it that way, the thing in the link box / URL bar would be a link to the query builder, rather than a link to the datastore download.

Solving the problem that way has some benefits:

 * It makes the query shareable and saveable
 * It means the query can easily be modified and updated

**Comment by andylolz** [comment]
Closing this one… but I’m still hopeful that the idea can be revived!

**Comment by JamesCoe** [comment]
@dalepotter Cheers for the document!

**Pull request closed without merging**
