### PR TITLE
Wrap everything in jquery ready function

### PR DESCRIPTION
**Pull request by andylolz**
Given you’re using jquery, I guess you should use one of these:
https://api.jquery.com/ready/

### CODE REVIEW

**Comment by hayfield** [comment]
Once the merge conflicts are sorted, this LGTM.

**Comment by andylolz** [comment]
Kk fixed.

**Comment by andylolz** [comment]
One process point… (not sure the most sensible place to put it!) I usually make the `dev` branch default, because it makes it much harder to send a PR to the wrong branch. I use [hub](https://hub.github.com) and it’s really nice to just type `hub pull-request` rather than reading the docs to remember how to send the PR to the right place / sending the PR to the wrong place and then panicking and hammering ^C.

**Comment by allthatilk** [comment]
@andylolz Yeah, the `master` and `live` thing is a historical setup problem we want to get rid of. I think we have those 3 atm as an interim setup up as we hope to eventually have `dev` as the default and `master` as production. Ultimately it's just another one of the idiosyncracies that come with so many repos that need changing and 3 devs working at maximum capacity on a wonky code base. These things will hopefully end up in the "let's get on and fix this" pipeline at some point in the future, but just not right now I'm afraid.

**Comment by andylolz** [comment]
Oh! I’d misunderstood – I thought you were proposing fewer branches, rather than just a renaming of existing branches. Renaming doesn’t sound useful to me – I don’t think it much matters what the branches are called. Of course the renaming itself would just be a case of:

```
git branch -m master dev
git branch -m live master
git push --all origin
```

…But presumably you’d have to update some deployment scripts… And it’ll break all clones… Not worth it imo, especially given capacity constraints.

**Comment by hayfield** [comment]
> …But presumably you’d have to update some deployment scripts

This is the main problem - there are lots of dependencies around branch names. It should be globally fixable in a reasonable amount of time by searching for `master` and `live`, though the lack of integration testing in many historical projects makes this a challenge.

**Comment by andylolz** [comment]
> And it’ll break all clones

This is a bit of a problem too… (Though ostensibly someone else’s problem!) There’s quite a lot of forks out there, so probably quite a lot of clones, too. I’m not sure what happens to forks when you rename branches - I don’t know if github is smart enough to figure out what happened.

This is just so your branches have idiomatic names?

**Pull request merged**
