### PR TITLE
Datastore API expects 'budget', not 'budgets'

### LINKED ISSUE #27: Failed CSV generation
After making a selection of the data I ma interested in and the URL is created, I get a page not found error 

url: http://datastore.iatistandard.org/api/1/access/budgets/by_country.csv?recipient-region=89&stream=True
screen shot 2017-01-18 at 11 43 06

Please assist if possible

### PR DESCRIPTION
**Pull request by andylolz**
Fixes #27.

### CODE REVIEW

**Comment by dalepotter** [comment]
Hi @andylolz - would you be able to merge upstream changes into this branch, then apply the latter change to the `templates/index.html` file.

This should then resolve the merge conflict and enable this to be merged.

**Comment by andylolz** [comment]
Oops sorry, yes. I should have seen this coming!

**Comment by andylolz** [comment]
I’ve done some criminal `git push --force` antics, just to keep the commit history tidy. Hope that’s okay.

**Comment by dalepotter** [comment]
Thanks for amending so quickly @andylolz - as the `git push --force` only affected your branch, we can turn a blind eye this time :-)

**Pull request merged**
