### PR TITLE
Split PHP from templates using twig

### PR DESCRIPTION
**Pull request by andylolz**
Templatizing the query builder (using twig) was something @dalepotter mentioned at TAG, so I’ve given it a go.

I’ve also tried adding bootstrap but I’ll send that as a separate PR.

Two things to consider:

 * This does require installing twig on the query builder server using composer
 * I’m not sure which version of PHP the query builder server runs. I’ve tested with PHP 5.6 only, but happy to test further

### CODE REVIEW

**Comment by andylolz** [comment]
I should add: this is very deliberately a copy paste with very little modification of the original PHP. I’d seek to make those sorts of changes as part of a separate pull request. The goal here is very specifically to templatize, with a tiny bit of HTML tidying thrown in.

**Comment by dalepotter** [comment]
Thanks for all this work @andylolz - looks good at first glance and great to have your contributions to improve the codebase.

We've added this to our list of maintenance tasks for the week, so will be able to take a look in more detail tomorrow. Will write back then!

**Comment by dalepotter** [comment]
Thanks again @andylolz - just had a chance to test this and looks good!

I will merge and update the install instructions to include the use of Composer.

**Comment by andylolz** [comment]
Brilliant! Thanks Dale!

**Pull request merged**
