### PR TITLE
Merge master to live

### PR DESCRIPTION
**Pull request by dalepotter**

### CODE REVIEW

**Comment by andylolz** [comment]
Can I ask: Why do you review when merging to `live`? I’m not sure I understand this workflow… Is it because internally you sometimes commit direct to `master`?

When stuff is blocked when merging to `live` (like IATI/IATI-Datastore#258) you’re left in a weird limbo where bad patches are left on your main development branch (`master`). Also, as a contributor it’s slightly weird figuring out how to resolve the issue. I can’t make changes to a PR from `master`, so I have to create a new PR to `master` and recommend that the blocked PR is subsequently updated.

It also means there’s potentially a long delay (from accepted PR to deployment) which means the feedback loop to the committer is broken down. So if the commit turns out to have been bad, the committer is less likely to check back and notice. (I wonder if that’s what happened with #33).

If it’s about more eyes, you could instead have multiple reviewers on the pull request to `master` and leave PRs to `live` unreviewed.

**Comment by hayfield** [comment]
The primary reason is a lack of a "only allow Pull Requests from these other branches" as part of Github's branch protection capabilities. Without this, if reviews are not required then a PR to the `live` branch looks the same as a PR to a `random-tiny-feature-branch`. This is bad. By requiring reviews, there is a visual distinction and removes the ability to accidentally merge to `live` by mis-reading a branch name.

**Comment by andylolz** [comment]
@hayfield yeah sure, having reviews switched on is fine… But… `master` to `live` should be a box tick exercise, shouldn’t it? I’m not sure it makes sense to actually be re-reviewing (and blocking) stuff that has already been reviewed… Again, I’m thinking specifically about IATI/IATI-Datastore#258.

**Comment by allthatilk** [comment]
@andylolz You're right that it is a box ticking exercise, we just have a lot of boxes to tick :) 

As @hayfield said, it's possible to merge to `live` from feature branches. PRs to `live` still need at least a quick look over to make sure they are what we think they are before they are approved for merging. Unfortunately, this stuff may end up behind the queue of other more urgent issues e.g improvements and modifications to the [Grand Bargain transparency dashboard](http://46.101.46.6/dashboard) and things like IATI/IATI-Dashboard#407 and IATI/IATI-Datastore#271. 

We recently released a post that details how we structure our workload and processes here if you're interested: http://www.aidtransparency.net/news/a-week-in-the-life-of-an-iati-developer (we typically allocate maintenance and small feature improvements for Mondays).

**Comment by andylolz** [comment]
Hi @allthatilk,

I totally understand you and the tech team are busy – indeed, that’s part of the reason I try as much as possible to investigate and fix these issues myself. In fact, I spent some time investigating and fixing one of the issues you mention above (IATI/IATI-Datastore#271).

I really don’t want to sound like I’m nagging! My point here was just: by revising your existing processes, you might be able to free up more time to work on some of these issues.

To go into a ridiculous level of detail re. IATI/IATI-Datastore#258:

 * IATI/IATI-Datastore#251 was reviewed and merged to `master`
 * in the internal PR from `master` to `live`, IATI/IATI-Datastore#251 was re-reviewed and blocked. I gather from the comments above that this re-review is non-standard (because `master` to `live` is a box-tick), but it worked in this case to flag a genuine problem
 * rather than reverting IATI/IATI-Datastore#251, it was left on `master`, leaving the repo in limbo (see [my comment above](https://github.com/IATI/IATI-Query-Builder/pull/47#issuecomment-318337757))
 * then, when an important fix (IATI/IATI-Datastore#272) needed to be merged to live and deployed, it wasn’t really possible because of the blockage
 * again, rather than reverting IATI/IATI-Datastore#251 (or implementing IATI/IATI-Datastore#272 as a hotfix, or other solutions) the repo was deployed from `master`. So IATI/IATI-Datastore#251 is on production now anyway (you can tell because [this hack](http://datastore.iatistandard.org/api/1/access/budgettt.Hey_look.A_custom_filename.csv) now 404s)

So as far as process goes:

 * I don’t think you should re-review when merging from `master` to `live`. But…
 * _If you do happen to re-review_, and you spot something that wasn’t picked up on the original feature review, then you should revert the feature on `master`. In the case of IATI/IATI-Datastore#251, I suppose that still needs to happen.

> We recently released a post that details how we structure our workload and processes here if you're interested

Yes – I read and enjoyed your blogpost! In fact, I’ve written some comments on it, though I wasn’t sure the best way to send those (since comments are ‘off’ on the blogpost).

**Comment by allthatilk** [comment]
Hi @andylolz !

You definitely have a valid point and we know our version control and deployment setup is less than ideal. Ideally we'd like to not have `live` branches at all and consistently treat `master` as the production branch.  Sadly, it's one of the things that just hasn't made it to the front of the queue yet, though I think we need to re-evaluate this if blocked changes are being deployed.

Speaking of, we definitely appreciate the work you've been doing on bug fixing. It's saved us so much time! Thank you for all your excellent work, it really helps us out! =)

I think it's really important to drill down into processes so your comments are definitely not considered nagging!  As for comments on my blog post, feel free to drop me an email =)

**Pull request merged**
