### PR TITLE
Fix ugly ids

### LINKED ISSUE #56: Make form element names and IDs human-readable
Presumably the original form here was generated with frontpage or something like that… The form elements have weird generated names and IDs. I suppose it might be possible to consider renaming as a breaking change, but:

 * I can’t imagine why third party tools would use the query builder as an unofficial API, rather than using the official datastore API directly.
 * The query builder says alpha all over it, so I don’t see why breaking changes would be a problem here anyway (but again: I wouldn’t consider this a breaking change).
 * Using human-readable names is nicer / self-explanatory etc

I mention this now, because I guess #55 is probably going to use the form element names, so it seems pertinent to change them.

### PR DESCRIPTION
**Pull request by andylolz**
# TO BE MERGED LAST

Fixes #56.

It’s likely this will cause a merge conflict for other PRs / they will cause a merge conflict here. Sorry about that! It affects quite a lot of code, so without me making assumptions about what will be merged, it’s inevitable.

### CODE REVIEW

**Comment by dalepotter** [comment]
Thanks for this one @andylolz - it will be very useful to resolve all of these id issues :-)

I'm going to suggest that we look at this one after all the current PRs are merged, given that - as you say - the changes here will likely cause merge conflicts without adding any user-facing functionality.

**Comment by andylolz** [comment]
That’s fine. I’m fixing merge conflicts on all my PRs whenever they come up.

**Comment by hayfield** [comment]
Note that some of the JS will need changing so that the link-updating works with this renaming.

**Comment by andylolz** [comment]
> Note that some of the JS will need changing so that the link-updating works with this renaming.

That’s done in 046419cb.

**Comment by andylolz** [comment]
New merge conflicts resolved. Should be ready to go.

**Comment by allthatilk** [comment]
Didn't spot that this one still needs more changes to the JS in order to fix IDs without breaking functionality. Sorry!

**Comment by andylolz** [comment]
I don’t understand… What is broken?

Here is a live demo of the javascript component, deployed from this branch:
https://andylolz.github.io/IATI-Query-Builder/

**Comment by hayfield** [comment]
merge conflict went wrong - is another commit since that deploy

**Comment by andylolz** [comment]
I’ve had another go at this in #86.

Just as a sort of retrospective on this: 7ab3ac60 wasn’t quite right… But bad merge conflict resolutions happen! In terms of process, though: after a commit to a PR branch (including a merge conflict resolution), the branch should probably be reviewed by someone other than the committer. In this case the commit, review and merge were all done by the same person.

**Pull request merged**
