### PR TITLE
Add endpoints js generate

### PR DESCRIPTION
**Pull request by dalepotter**

### CODE REVIEW

**Comment by andylolz** [comment]
Would be good to add validation for impossible stuff re dates, but in any case that needs to be added more generally (e.g. in javascript, an error alert should probably be shown when you select country and region).

On dates… I wonder if ‘after’ should actually be shown before ‘before‘? If you think of them defining a range for e.g. the start date, it’s more natural to set the lower bound of that range first, and the upper bound second.

**Comment by dalepotter** [comment]
Thanks for this @andylolz - we're out of build time on this one, so we're looking to merge this one down to `dev` today and then everything in `dev` to `master` today for deployment, so we won't be able to look at any modifications at this time.  Feel free to open an issue for this though.

**Comment by andylolz** [comment]
> we're looking to merge this one down to dev today and then everything in `dev` to `master` today for deployment, so we won't be able to look at any modifications at this time. Feel free to open an issue for this though.

Sent as PR: #82.

**Comment by dalepotter** [comment]
> we're looking to merge this one down to dev today and then everything in dev to master today for deployment, so we won't be able to look at any modifications at this time. Feel free to open an issue for this though.

> Sent as PR: #82.

Sorry that was my bad - @hayfield started working on it independently around the same time as I was posting...

**Comment by andylolz** [comment]
No problem! I did it because you said you didn’t have time to do it.

I did send #79 yesterday, though… So I’m not really sure why #80 (which duplicates it and uses an inline style) was merged.

**Pull request merged**
