### PR TITLE
Add JS-based linkgen

### PR DESCRIPTION
**Pull request by hayfield**
Provide a link that updates on the client side when things in the form are changed.

* Existing IDs used, so as to prevent having to modify anything that already exists.
* No styling has been added.
* JS not in external file. Could be moved there is desired, though that leads to another HTTP request.

### CODE REVIEW

**Comment by hayfield** [comment]
Totally missed that jQuery has been included on the page! >.<

**Comment by andylolz** [comment]
> Totally missed that jQuery has been included on the page! >.<

I really wanted to point that out, but felt bad for interfering!

**Comment by andylolz** [comment]
btw just in case it is useful (but very possible it isn’t!) this does roughly the same thing:
https://github.com/andylolz/IATI-Query-Builder/blob/947a52a2/static/js/table.js#L24-L65

**Comment by hayfield** [comment]
Ready for after #58 is merged.

**Comment by andylolz** [comment]
I don’t follow this:

> This is partly due to the stupid computer-generated ids that are invalid at HTML4 due to the inclusion of square brackets.

> * Existing IDs used, so as to prevent having to modify anything that already exists.

What does “anything that already exists” refer to?

**Comment by hayfield** [comment]
> What does “anything that already exists” refer to?

All the PHP and jazz - changing that is a separate task.

**Comment by andylolz** [comment]
Ahhhh okay. Yep – that is totally fine (because it sounds like you are saying there is a chance this will be changed at a later date, which I am happy about).

**Comment by andylolz** [comment]
@hayfield: Why does the javascript inspect the `aria-label` rather than the `value` of the radios? `aria-label` isn’t supposed to be used in this way, whereas `value` is.

**Comment by hayfield** [comment]
> @hayfield: Why does the javascript inspect the aria-label rather than the value of the radios? 

Reading right-to-left it was the first thing I saw that had somewhat relevant information. I'll, um, blame the silly ids for obscuring the correct thing to use!

**Pull request merged**
